# Generated by Django 4.1.3 on 2022-11-03 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(blank=True, max_length=255)),
                ('translation', models.CharField(blank=True, max_length=255)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tlearn.collection')),
            ],
        ),
    ]
