# Generated by Django 4.1.3 on 2022-11-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlearn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carduserprogress',
            name='time_created',
            field=models.DateTimeField(verbose_name='%Y-%m-%d %H:%M'),
        ),
    ]
