# Generated by Django 4.1.3 on 2022-11-06 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tlearn", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rotation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("period", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.CharField(blank=True, max_length=255)),
                (
                    "active_collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tlearn.collection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CardProgress",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("time_updated", models.DateTimeField(auto_now=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tlearn.card"
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tlearn.collection",
                    ),
                ),
                (
                    "rotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tlearn.rotation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tlearn.user"
                    ),
                ),
            ],
        ),
    ]
