# Generated by Django 4.1.3 on 2022-11-20 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlearn', '0002_alter_carduserprogress_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carduserprogress',
            name='time_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
