# Generated by Django 4.1.3 on 2022-11-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tlearn", "0002_rotation_user_cardprogress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
