# Generated by Django 4.1.3 on 2022-12-01 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlearn', '0002_alter_carduserprogress_penalty_step_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carduserprogress',
            old_name='penalty_step_id',
            new_name='penalty_state_id',
        ),
    ]
