# Generated by Django 4.1.3 on 2022-11-06 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tlearn", "0004_alter_collection_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="active_collection",),
        migrations.DeleteModel(name="CardProgress",),
        migrations.DeleteModel(name="Rotation",),
        migrations.DeleteModel(name="User",),
    ]
