# Generated by Django 4.1.3 on 2022-11-08 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlearn', '0005_remove_user_active_collection_delete_cardprogress_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
