# Generated by Django 4.1.3 on 2022-11-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tlearn', '0006_delete_card_delete_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testov',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
