# Generated by Django 4.1.3 on 2022-11-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlearn', '0007_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testov',
            name='test_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
