# Generated by Django 4.1.3 on 2022-12-05 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tlearn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='active_collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tlearn.cardcollection'),
        ),
    ]
